import type { CompanyDetailKey } from './es';

export const companyDetailEn: Record<CompanyDetailKey, string> = {
  // ── Search ──
  'search.placeholder': 'Search ticker...',
  'search.go': 'Go',
  'search.searching': 'Searching…',
  'search.noMatches': 'No matches',

  // ── Loading / Error states ──
  'loading': 'Loading information for {symbol}...',
  'noUsEquivalent': 'This CEDEAR has no US-listed equivalent.',
  'noUsEquivalentSub': 'Cannot retrieve information from FMP.',
  'noProfile': 'No information found for {symbol}.',

  // ── Tabs ──
  'tabs.info': 'Info',
  'tabs.charts': 'Charts',
  'tabs.advanced': 'Advanced',
  'tabs.news': 'News',

  // ── Info tab ──
  'info.companyData': 'Company data',
  'info.etfData': 'ETF data',
  'info.sector': 'Sector',
  'info.industry': 'Industry',
  'info.marketCap': 'Market Cap',
  'info.beta': 'Beta',
  'info.avgVolume': 'Avg. Volume',
  'info.country': 'Country',
  'info.ipo': 'IPO',
  'info.inception': 'Inception',
  'info.web': 'Web',
  'info.noDescription': 'No description available.',

  // ── Charts tab ──
  'chart.price': 'Price (1 year)',
  'chart.priceHelp': 'Daily closing price over the past year on a US exchange. Green if up, red if down compared to the start of the period.',
  'chart.priceTooltip': 'Price',
  'chart.noPrice': 'No price data.',
  'chart.volume': 'Volume (1 year)',
  'chart.volumeHelp': 'Number of shares traded per day. High volume indicates greater liquidity and market interest.',
  'chart.volumeTooltip': 'Volume',
  'chart.revenue': 'Revenue & Net Income',
  'chart.revenueHelp': 'Revenue (bars): total annual income. Net Income (line): net profit after taxes and expenses. Sustained growth indicates a healthy business.',
  'chart.noFinancials': 'No financial data available.',
  'chart.margins': 'Margins (%)',
  'chart.marginsHelp': 'Gross: % of revenue remaining after cost of goods. Operating: after operating expenses. Net: final profit as % of revenue. Stable or growing margins indicate efficiency.',
  'chart.marginGross': 'Gross',
  'chart.marginOperating': 'Operating',
  'chart.marginNet': 'Net',
  'chart.eps': 'EPS',
  'chart.epsHelp': 'Earnings Per Share: net income divided by total shares outstanding. A growing EPS suggests increased profitability per share for the investor.',

  // ── Advanced tab ──
  'adv.loading': 'Loading advanced data...',
  'adv.noData': 'Could not load advanced data.',
  'adv.noScores': 'No score data available.',
  'adv.scoresTitle': 'Scores & Valuation',
  'adv.scoresHelp': 'Altman Z-Score: bankruptcy risk (>2.99 safe, 1.81-2.99 grey zone, <1.81 danger). Piotroski F-Score: value quality (0-9, ≥7 strong). DCF: intrinsic value estimated by discounted cash flow.',
  'adv.dcfFairValue': 'DCF (fair value)',
  'adv.currentPrice': 'Current price',
  'adv.signal': 'Signal',
  'adv.undervalued': 'Undervalued',
  'adv.overvalued': 'Overvalued',
  'adv.valuation': 'Valuation (P/E & P/B)',
  'adv.valuationHelp': 'P/E (bars): price divided by earnings — how many years of earnings you pay. P/B (line): price vs book value. Low values may indicate undervaluation.',
  'adv.profitability': 'Profitability (ROE & ROA)',
  'adv.profitabilityHelp': 'ROE: return on equity — how much is generated per dollar invested by shareholders. ROA: return on total assets. Higher values indicate better efficiency.',
  'adv.cashFlow': 'Cash Flow',
  'adv.cashFlowHelp': 'Operating CF (bars): cash generated by operations. Free CF (line): cash available after capital investments. Positive and growing FCF is a sign of financial strength.',
  'adv.capitalStructure': 'Capital Structure',
  'adv.capitalHelp': 'Equity (green) + Liabilities (blue) = Total Assets. Net Debt (line): total debt minus cash. A growing equity proportion indicates greater strength.',
  'adv.equity': 'Equity',
  'adv.liabilities': 'Liabilities',
  'adv.netDebt': 'Net Debt',
  'adv.leverage': 'Leverage',
  'adv.leverageHelp': 'Debt/Equity (bars): how much debt per dollar of equity. Current Ratio (line): current assets / current liabilities — >1 indicates short-term solvency.',

  // ── News tab ──
  'news.loading': 'Loading news...',
  'news.empty': 'No news available for {symbol}.',
  'news.error': 'Could not load news.',
};
