export { TechnicalDetail } from './TechnicalDetail';
export { SentimentDetail } from './SentimentDetail';
export { ValuationDetail } from './ValuationDetail';
export { GrowthDetail } from './GrowthDetail';
export { FundamentalsDetail } from './FundamentalsDetail';
export { WarrenBuffettDetail } from './WarrenBuffettDetail';
export { StanleyDruckenmillerDetail } from './StanleyDruckenmillerDetail';
export { RakeshJhunjhunwalaDetail } from './RakeshJhunjhunwalaDetail';
export { PhilFisherDetail } from './PhilFisherDetail';
